### ISSUE TITLE
state left behind when a test fails

### ISSUE THREAD

**Issue by JonJagger** [cyber-dojo-retired/runner-stateful#6]
when a test fails it can leave state behind. For example it can leave a container which holds onto a volume. 
<eg>
$ ./pipe_build_up_test.sh 
........
  1) Error:
RunAlpineTest#test_
hex '2321',
'[Ubuntu] new files are added with owner/group/permissions and all previous files are unchanged':
ArgumentError: kata_id:exists
    /app/src/docker_runner_mix_in.rb:279:in `fail_kata_id'
    /app/src/shared_volume_runner.rb:260:in `refute_kata_exists'

$ docker volume ls | grep 2321
...
local               cyber_dojo_kata_volume_runner_3759D23210
...
$ docker volume rm cyber_dojo_kata_volume_runner_3759D23210
Error response from daemon: unable to remove volume: remove cyber_dojo_kata_volume_runner_3759D23210: volume is in use - [5c134e02a70ceb09d3bc4b94bebd844cb20beee64ac83b70982216921cd1d670]

$ docker rm -f 5c134e02a70ceb09d3bc4b94bebd844cb20beee64ac83b70982216921cd1d670
5c134e02a70ceb09d3bc4b94bebd844cb20beee64ac83b70982216921cd1d670

$ docker volume rm cyber_dojo_kata_volume_runner_3759D23210
</eg>

Unless you clear out the state the same test will fail when you re-run the tests since it will fail to create the volume.
However, I'd like to leave the container for a failed test undeleted since that way I can shell into it (eg for debugging). 
What I need is to clear out old-state at the start before the tests run.
To do that I need the containers to be findable. I could make all the containers have a name that starts with a given prefix eg runner_test_4557 and ends in something generated by uuidgen . Then I could find them all and do a 
[docker rm --force --volumes NAME]

**Comment by JonJagger** [comment]
Fixed this as describe the previous comment.
